import type { AiPluginManifest } from "../plugin-manifest.js";

const textFields = [
  {
    defaultValue: 0.7,
    key: "temperature",
    label: "Temperature",
    mapsTo: "request.params" as const,
    max: 2,
    min: 0,
    step: 0.1,
    type: "slider" as const,
  },
  {
    defaultValue: 2048,
    key: "maxTokens",
    label: "Max tokens",
    mapsTo: "request.params" as const,
    max: 8192,
    min: 128,
    step: 128,
    type: "number" as const,
  },
];

const models = [
  {
    credits: 1,
    displayName: "Gemini-3.1-pro",
    logoKey: "google-gemini",
    manufacturer: "Gemini",
    modelKey: "gemini-3.1-pro",
    path: "/v1beta/models/{model}:generateContent",
    protocol: "gemini",
    sortOrder: 10,
    upstreamModel: "gemini-3.1-pro-preview",
  },
  {
    credits: 0.5,
    displayName: "Gemini-3.5-flash",
    logoKey: "google-gemini",
    manufacturer: "Gemini",
    modelKey: "gemini-3.5-flash",
    path: "/v1beta/models/{model}:generateContent",
    protocol: "gemini",
    sortOrder: 20,
    upstreamModel: "gemini-3.5-flash-preview",
  },
  {
    credits: 2,
    displayName: "GPT-5.6-sol",
    logoKey: "openai",
    manufacturer: "GPT",
    modelKey: "gpt-5.6-sol",
    path: "/v1/chat/completions",
    protocol: "chat-completions",
    sortOrder: 30,
    upstreamModel: "gpt-5.6-sol",
  },
  {
    credits: 1,
    displayName: "GPT-5.6-terra",
    logoKey: "openai",
    manufacturer: "GPT",
    modelKey: "gpt-5.6-terra",
    path: "/v1/chat/completions",
    protocol: "chat-completions",
    sortOrder: 40,
    upstreamModel: "gpt-5.6-terra",
  },
  {
    credits: 2,
    displayName: "GPT-5.5",
    logoKey: "openai",
    manufacturer: "GPT",
    modelKey: "gpt-5.5",
    path: "/v1/chat/completions",
    protocol: "chat-completions",
    sortOrder: 50,
    upstreamModel: "gpt-5.5",
  },
  {
    credits: 2.5,
    displayName: "Claude-Opus-5",
    logoKey: "claude",
    manufacturer: "Claude",
    modelKey: "claude-opus-5",
    path: "/v1/messages",
    protocol: "claude",
    sortOrder: 60,
    upstreamModel: "claude-opus-5",
  },
  {
    credits: 1.5,
    displayName: "Claude-Sonnet-5",
    logoKey: "claude",
    manufacturer: "Claude",
    modelKey: "claude-sonnet-5",
    path: "/v1/messages",
    protocol: "claude",
    sortOrder: 70,
    upstreamModel: "claude-sonnet-5",
  },
  {
    credits: 2,
    displayName: "Claude-Opus-4-8",
    logoKey: "claude",
    manufacturer: "Claude",
    modelKey: "claude-opus-4-8",
    path: "/v1/messages",
    protocol: "claude",
    sortOrder: 80,
    upstreamModel: "claude-opus-4-8",
  },
] as const;

function routeKey(modelKey: string): string {
  return `text.${modelKey.replace(/\./g, "-")}`;
}

export const aittcoTextRelayManifest: AiPluginManifest = {
  credentials: {
    envKeys: ["AITTCO_TEXT_RELAY_API_KEY"],
    fields: [
      {
        key: "apiKey",
        label: "Aittco Text Relay API Key",
        required: true,
        secret: true,
      },
    ],
    type: "bearer",
  },
  description: "Gemini, GPT, and Claude text generation through the Aittco relay.",
  displayName: "Aittco Text Relay",
  modality: "text",
  models: models.map((model) => ({
    capabilities: { supportsStreaming: false },
    defaultRouteKey: routeKey(model.modelKey),
    displayName: model.displayName,
    modality: "text",
    modelFamily: model.modelKey,
    modelKey: model.modelKey,
    sortOrder: model.sortOrder,
    uiSchema: {
      fields: textFields,
      logoKey: model.logoKey,
      manufacturer: model.manufacturer,
      panelLayout: "text",
    },
  })),
  packageKey: "aittco.text-relay",
  pricing: models.map((model) => ({
    metadata: { source: "aittco-text-relay" },
    minChargeCredits: model.credits,
    model: model.modelKey,
    provider: "aittco-text-relay",
    route: routeKey(model.modelKey),
    unit: "text_generation" as const,
    unitCredits: model.credits,
  })),
  provider: {
    capabilities: {
      protocols: ["gemini", "chat-completions", "claude"],
      timeoutMs: 60_000,
    },
    defaultBaseUrl: "https://api.aittco.com",
    key: "aittco-text-relay",
    kind: "aittco-text-relay",
    name: "Aittco Text Relay",
  },
  routes: models.map((model) => ({
    mode: "sync" as const,
    modality: "text" as const,
    modelFamily: model.modelKey,
    modelKey: model.modelKey,
    path: model.path,
    priority: 100,
    requestConfig: {
      apiMode: model.protocol,
      model: model.upstreamModel,
      path: model.path,
      protocol: model.protocol,
      timeoutMs: 60_000,
    },
    routeKey: routeKey(model.modelKey),
    routeLabel: "默认线路",
    timeoutMs: 60_000,
  })),
  tests: models.map((model) => ({
    expected: { status: "succeeded" as const },
    key: `basic-${model.modelKey}`,
    label: `${model.displayName} 基础文本测试`,
    request: {
      messages: [{ content: "请仅回复：测试成功", role: "user" as const }],
    },
    routeKey: routeKey(model.modelKey),
  })),
  version: "1.0.0",
};
