export type ConsoleScope = "self" | "platform";
export type ConsoleSource = "workflow" | "workbench" | "agent" | "unknown";
export type ConsolePage<T> = {
    items: T[];
    nextCursor: string | null;
    hasMore: boolean;
    asOf: string;
    from: string;
    to: string;
    scope: ConsoleScope;
    pageSize: number;
};
export type ConsoleUsage = {
    id: string;
    usageEventId: string | null;
    tenantId: string;
    userId: string | null;
    projectId: string | null;
    source: ConsoleSource;
    taskId: string | null;
    nodeRunId: string | null;
    modelId: string | null;
    routeId: string | null;
    modality: string;
    status: string;
    executionStatus: string;
    billingStatus: string;
    chargedCredits: string | null;
    inputTokens: number | null;
    outputTokens: number | null;
    quantity: string | null;
    unit: string | null;
    createdAt: string;
    dataQuality: "partial" | "legacy";
};
export type ConsoleTaskTimelineItem = {
    id: string;
    kind: "task" | "node" | "event";
    label: string;
    status: string | null;
    nodeRunId: string | null;
    executionId: string | null;
    attempt: number | null;
    createdAt: string;
    finishedAt: string | null;
};
export type ConsoleTaskAttempt = {
    id: string;
    nodeRunId: string | null;
    executionId: string | null;
    attempt: number | null;
    operation: string;
    transportStatus: string;
    trafficClass: string;
    providerRequestId: string | null;
    providerTaskId: string | null;
    traceId: string | null;
    httpStatus: number | null;
    latencyMs: number | null;
    connectionName: string | null;
    upstreamModel: string | null;
    productModelKey: string | null;
    routeKey: string | null;
    routeLabel: string | null;
    errorCode: string | null;
    requestStartedAt: string | null;
    requestCompletedAt: string | null;
    createdAt: string;
};
export type ConsoleTaskDiagnostics = {
    actorUserId: string | null;
    billedUserId: string | null;
    traceIds: string[];
    providerRequestIds: string[];
    providerTaskIds: string[];
    connectionNames: string[];
    upstreamModels: string[];
    errorCodes: string[];
};
export type ConsoleTask = {
    id: string;
    source: ConsoleSource;
    sourceId: string;
    tenantId: string;
    userId: string | null;
    projectId: string | null;
    status: string;
    createdAt: string;
    startedAt: string | null;
    finishedAt: string | null;
    dataQuality: "partial";
    timeline?: ConsoleTaskTimelineItem[];
    attempts?: ConsoleTaskAttempt[];
    diagnostics?: ConsoleTaskDiagnostics;
};
export type ConsoleCall = {
    id: string;
    tenantId: string;
    workflowRunId: string | null;
    nodeRunId: string | null;
    modelId: string | null;
    routeId: string | null;
    productModelKey: string | null;
    routeKey: string | null;
    routeLabel: string | null;
    status: string;
    /** `summary` is historical/runtime outcome data; only `request` is a physical upstream request. */
    recordLevel: "summary" | "request";
    operation: "unknown" | "generate" | "submit" | "poll" | "stream";
    trafficClass: "user_generation" | "admin_test" | "agent_control" | "system" | "unknown";
    transportStatus: string | null;
    executionId: string | null;
    attempt: number | null;
    httpStatus: number | null;
    latencyMs: number | null;
    inputTokens: number | null;
    outputTokens: number | null;
    createdAt: string;
    dataQuality: "partial" | "legacy";
    actorUserId?: string | null;
    billedUserId?: string | null;
    providerRequestId?: string | null;
    providerTaskId?: string | null;
    traceId?: string | null;
    errorCode?: string | null;
    connectionName?: string | null;
    upstreamModel?: string | null;
};
export type ConsoleActivity = {
    id: string;
    tenantId: string | null;
    usageEventId: string | null;
    entryType: string;
    amountCredits: string;
    direction: "credit" | "debit";
    createdAt: string;
};
export type ConsoleOverview = {
    scope: ConsoleScope;
    asOf: string;
    from: string;
    to: string;
    usage: {
        total: number;
        settled: number;
        unbilled: number;
        chargedCredits: string;
    };
    tasks: {
        total: number;
        bySource: Record<string, number>;
    };
    generation: {
        total: number;
        succeeded: number;
        failed: number;
        canceled: number;
        pendingOrUnknown: number;
        successRate: number | null;
    };
    upstream: {
        total: number;
        operationCoverage: "legacy" | "request";
        requestSuccessRate: number | null;
        adminTestTotal?: number;
        adminTestSuccessRate?: number | null;
        otherTotal?: number;
        otherSuccessRate?: number | null;
    } | null;
    dataQuality: "partial";
};
