import type { CanvasAgentV4Task } from "./canvasAgentV4Types";
import { useState } from "react";

export function CanvasAgentV4TaskPanel({ task, onSubmit, onApprove, onCancel, onRetry, onUndo }: { task?: CanvasAgentV4Task; onSubmit?: (prompt: string) => void; onApprove?: () => void; onCancel?: () => void; onRetry?: (itemId: string) => void; onUndo?: (revision: number) => void }) {
  const [prompt, setPrompt] = useState("");
  if (!task) return <aside aria-label="Canvas Agent V4 task panel"><h2>Canvas Agent V4</h2><form onSubmit={(event) => { event.preventDefault(); if (prompt.trim()) { onSubmit?.(prompt.trim()); setPrompt(""); } }}><input aria-label="V4 prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="描述要生成的商品套图" /><button type="submit">发送</button></form></aside>;
  const failed = task.generationItems?.filter((item) => item.status === "failed") ?? [];
  const succeeded = task.generationItems?.filter((item) => item.status === "succeeded") ?? [];
  const appliedRevision = task.events.reduce<number | undefined>((revision, event) => typeof event.revision === "number" ? event.revision : revision, undefined);
  return <aside aria-label="Canvas Agent V4 task panel"><h2>Canvas Agent V4</h2><p>状态：{task.status}</p><p>事件：{task.events.length}</p><form onSubmit={(event) => { event.preventDefault(); if (prompt.trim()) { onSubmit?.(prompt.trim()); setPrompt(""); } }}><input aria-label="V4 prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="继续描述或修复某一页" /><button type="submit">发送</button></form>{task.status === "waiting_for_approval" && <button type="button" onClick={onApprove}>批准执行</button>}{!['succeeded', 'failed', 'cancelled'].includes(task.status) && <button type="button" onClick={onCancel}>取消任务</button>}{succeeded.length > 0 && <section aria-label="已生成结果"><h3>已生成 {succeeded.length} 项</h3>{succeeded.map((item) => <div key={item.itemId}>{item.itemId}{item.assetId ? ` · ${item.assetId}` : ""}</div>)}</section>}{failed.map((item) => <button key={item.itemId} type="button" onClick={() => onRetry?.(item.itemId)}>重试 {item.itemId}</button>)}{appliedRevision !== undefined && onUndo && <button type="button" onClick={() => onUndo(appliedRevision)}>撤销交付</button>}</aside>;
}
