import { describe, expect, test } from 'vitest';

import {
  IMAGE_FLOATING_TOOLBAR_BUTTON_SIZE,
  IMAGE_FLOATING_TOOLBAR_DIVIDER_HEIGHT,
  IMAGE_FLOATING_TOOLBAR_GAP,
  IMAGE_FLOATING_TOOLBAR_ICON_SIZE,
  IMAGE_FLOATING_TOOLBAR_ITEM_GAP,
  IMAGE_FLOATING_TOOLBAR_PADDING,
  IMAGE_FLOATING_TOOLBAR_RADIUS,
  IMAGE_FLOATING_TOOLBAR_TOOLTIP_FONT_SIZE,
  IMAGE_MENU_ITEM_MIN_HEIGHT,
  IMAGE_MENU_SURFACE_Z_INDEX,
  IMAGE_MODEL_MENU_LABEL_FONT_SIZE,
  IMAGE_MODEL_MENU_LABEL_FONT_WEIGHT,
  IMAGE_MODEL_MENU_WIDTH,
} from './imageMenuStyles';

describe('image menu style tokens', () => {
  test('keeps image menus above floating toolbars with add-menu density', () => {
    expect(IMAGE_MENU_SURFACE_Z_INDEX).toBeGreaterThanOrEqual(10020);
    expect(IMAGE_MENU_ITEM_MIN_HEIGHT).toBe(38);
    expect(IMAGE_MODEL_MENU_WIDTH).toBe(320);
    expect(IMAGE_MODEL_MENU_LABEL_FONT_SIZE).toBe(12);
    expect(IMAGE_MODEL_MENU_LABEL_FONT_WEIGHT).toBe(700);
  });

  test('keeps selected image floating toolbar compact', () => {
    expect(IMAGE_FLOATING_TOOLBAR_BUTTON_SIZE).toBe(36);
    expect(IMAGE_FLOATING_TOOLBAR_ICON_SIZE).toBe(18);
    expect(IMAGE_FLOATING_TOOLBAR_PADDING).toBe('4px 10px');
    expect(IMAGE_FLOATING_TOOLBAR_GAP).toBe(10);
    expect(IMAGE_FLOATING_TOOLBAR_ITEM_GAP).toBe(4);
    expect(IMAGE_FLOATING_TOOLBAR_RADIUS).toBe(20);
    expect(IMAGE_FLOATING_TOOLBAR_DIVIDER_HEIGHT).toBe(20);
    expect(IMAGE_FLOATING_TOOLBAR_TOOLTIP_FONT_SIZE).toBe(12);
  });
});
