export const IMAGE_MENU_SURFACE_Z_INDEX = 10020;
export const IMAGE_MENU_ITEM_MIN_HEIGHT = 38;
export const IMAGE_MODEL_MENU_WIDTH = 320;
export const IMAGE_MODEL_MENU_LABEL_FONT_SIZE = 12;
export const IMAGE_MODEL_MENU_LABEL_FONT_WEIGHT = 700;
